export const workoutsConstants = {
  GET_WORKOUTS_LIST: 'GET_WORKOUTS_LIST',
  SET_WORKOUTS_LIST: 'SET_WORKOUTS_LIST',
  INIT_WORKOUT_SELECTION: 'INIT_WORKOUT_SELECTION',
  SELECT_WORKOUT: 'SELECT_WORKOUT',
  CLEAR_SELECTED_WORKOUT: 'CLEAR_SELECTED_WORKOUT',
};
