export const workoutsConstants = {
  GET_WORKOUTS_LIST: 'GET_WORKOUTS_LIST',
  SET_WORKOUTS_LIST: 'SET_WORKOUTS_LIST',
  INIT_WORKOUT_SELECTION: 'INIT_WORKOUT_SELECTION',
  SET_NEW_WORKOUT: 'SET_NEW_WORKOUT',
  CLEAR_NEW_WORKOUT: 'CLEAR_NEW_WORKOUT',
};
