export const userConstants = {
  GET_USER_AT_LOGIN: 'GET_USER_AT_LOGIN',
  GET_USER_AT_REGISTER: 'GET_USER_AT_REGISTER',
  LOGOUT_USER: 'LOGOUT_USER',
  GET_USER_AT_FB_LOGIN: 'GET_USER_AT_FB_LOGIN',
  SET_USER_SUCCESS: 'SET_USER_SUCCESS',
  SET_USER_CLEAR: 'SET_USER_CLEAR',
};
